# Site settings
title: Rudy De Busscher
twitter_username: rdebusscher
name: Rudy De Busscher

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://www.atbash.be
 - title: GitHub
   url: https://github.com/rdebusscher
 - title: LinkedIn
   url: https://www.linkedin.com/in/rudy-de-busscher-71480036/

#Any buzzword skills you want to include
skills:
 - Java
 - Java EE
 - JSF
 - PrimeFaces
 - JPA
 - JAX-RS
 - OAuth2 / Open Id Connect
 - Tech Architecture


#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://www.atbash.be/feed/

#Work experience is required
roles:
 - title: Senior Java EE Developer
   start: may 2011
   end: Ongoing
   employer: C4J
   description: Various Web applications for customers with Java EE 7.
 

#Education is required
education:
 - level: Bio ingenieur
   date: 1998
   subject: Artificial Intelligence and Computer Science
   school: K.U.Leuven (Belgium)

#This section is optional (as is the image link below)

#List of interesting Github repo/projects to include - optional
github:
 - atbashEE/atbash-octopus

#Stackoverflow flair is optional

#Mobile apps section is optional

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   TODO
