# Site settings
title: Rudy De Busscher
twitter_username: rdebusscher
name: Rudy De Busscher

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://www.atbash.be
 - title: GitHub
   url: https://github.com/rdebusscher
 - title: LinkedIn
   url: https://www.linkedin.com/in/rudy-de-busscher-71480036/

#Any buzzword skills you want to include
skills:
 - Java
 - Java EE
 - PrimeFaces / JSF
 - JPA
 - JAX-RS
 - OAuth2 / OpenId Connect
 - JWT
 - CDI / EJB 3.x
 - Tech Architecture


#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://www.atbash.be/feed/

#Work experience is required
roles:
 - title: Senior Java EE Developer
   start: may 2011
   end: Ongoing
   employer: C4J
   description: Various Web applications for customers with Java EE 7.
 - title: Expert member of JSR-375 : Java EE Security API
   start: feb 2015
   end: oct 2017
   employer: Individual
   description: Design and implement the new Java EE Security API and implementation together with the Expert group.
 - title: Java Developer
   start: may 1998
   end: april 2011
   employer: (Real) Dolmen
   description: Various applications for customers (First Oracle Forms, later with Java EE).
 

#Education is required
education:
 - level: Bio ingenieur
   date: 1993
   subject: Agriculture and gen technology
   school: K.U.Leuven (Belgium)

#This section is optional (as is the image link below)

#List of interesting Github repo/projects to include - optional
github:
 - atbashEE/atbash-octopus

#Stackoverflow flair is optional

#Mobile apps section is optional

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   How should my next job look like?  
   Design the Technical solution and help implementing a (Web) Application using Java EE/Jakarta EE and/or MicroProfile.io.  
   Implement authentication and authorization using OpenIdConnect / Oauth2 / JBoss Keycloack / ...  
   Since I don't know anything about Spring framework, JavaScript frameworks (Angular, ReactJS, vue.js, ...) or Docker/Kubernetes I can't help when project uses these.  
   Coach other team members to have the best possible solution in terms of code quality.
